### ISSUE TITLE
Feat sasm admin story page remaining task

### ISSUE THREAD

**Issue by sejongk** [sdp-tech/SASM_FE#140]
## Description
SASM Admin Story 페이지 남은 작업 처리
## To-Do
- [x] rep_pic API 변경 반영
- [x] rep_pic 이미지 미리보기(preview)
- [x] place API 연동 후 place 목록 select box 제공
