### ISSUE TITLE
노션 에러 목록에서 FE 수정 부분

### ISSUE THREAD

**Issue by lina1919** [sdp-tech/SASM_FE#178]
## Description
- 노션에서 SDP 학회원들이 작성한 에러 목록 중, 프론트에서 수정이 필요한 부분

## To-Do
- [x] 회원 가입 시 '존재하지 않는 닉네임입니다' 에서 '사용가능한 닉네임입니다'로 변경
- [x] 회원 가입 시 '존재하지 않는 이메일입니다' 에서 '사용가능한 이메일입니다'로 변경
- [x] Naver Corp가 뜨는 것 삭제
- [x] Place Detail의 3장의 사진들을 클릭 가능하게 링크 달기
- [x] 크롬 화면 100%일 때 잘리는 화면들 존재
- [x] 소셜로그인에서 카카오톡 네모에서 동그라미로 사진 변경 필요
- [x] 장소 검색 시 검색 결과의 장소들이 지도에 뜨게 변경

## ETC
추후 구현 불가능한 것을 삭제하거나 추가되는 에러 추가해도 됩니다

**Comment by dgfh0450** [comment]
장소 검색 시 검색 결과 장소들이 지도에 뜨게 변경 -> #174 업로드 완료
