### ISSUE TITLE
검색 엔진 최적화(SEO)

### ISSUE THREAD

**Issue by sejongk** [sdp-tech/SASM_FE#293]
## Description
- 구글, 네이버 검색엔진에서 SASM과 관련된 키워드에 대해 검색 시, SASM에 대해 적절한 정보를 보여주도록 robots.txt 파일 생성
- 메인 페이지 외 다른 페이지에 접근하지 못하도록 규칙을 설정하여 과도한 크롤링으로 인한 요청 과부하 방지 필요
- 우선적으로 구글, 네이버 검색 엔진에 대해서만 적용
- 검색엔진 크롤러가 페이지를 잘 크롤링할 수 있도록 구글 검색엔진 최적화 가이드에 따라 페이지 최적화하기

## ToDos
- [x] robots.txt 파일에서 Disallow 규칙 추가, User-agent를 구글과 네이버로 한정
- [x] 사이트맵 생성
- [ ] navigate되는 행위를 a 태그, href 속성으로 대체하기
- [ ] 모든 장소 및 스토리 url로 접근 가능하도록 하기

## Etc
사이트맵 생성 - https://ujeon.medium.com/react-%EB%A6%AC%EC%95%A1%ED%8A%B8-%EC%9B%B9%EC%82%AC%EC%9D%B4%ED%8A%B8-%EC%82%AC%EC%9D%B4%ED%8A%B8%EB%A7%B5-%EB%A7%8C%EB%93%A4%EA%B8%B0-1116ff8b6c2a
구글 검색엔진 최적화 가이드 - https://developers.google.com/search/docs/fundamentals/seo-starter-guide?hl=ko#createsimplenavpage

**Comment by sejongk** [comment]
현재 빌드 이후에는 public 폴더에 있는 sitemap.xml이 외부에서 접근이 안됨. 추가 조치 필요

**Comment by sejongk** [comment]
@dgfh0450 React SEO 참고 자료 공유합니다.
React Link 사용하기
* https://gomgomkim.tistory.com/9
* https://velog.io/@seong-dodo/React-Link%EC%99%80-NavLink

Pre-rendering 적용하기
* https://velog.io/@ouo_yoonk/react%EC%97%90%EC%84%9C-SEO
* https://ahrefs.com/blog/react-seo/
* https://velog.io/@euisuk95/React-Helmet%EA%B3%BC-React-Snap%EB%A5%BC-%EC%9D%B4%EC%9A%A9%ED%95%9C-SEO
* https://satisfactoryplace.tistory.com/131
