### ISSUE TITLE
Story 리팩토링 시 FE 코드 수정

### ISSUE THREAD

**Issue by kjiyun** [sdp-tech/SASM_FE#367]
## Description
- BE story 코드 수정하면서 이에 맞춰서 FE 코드 수정

## To-Do
- [ ] story comment url 수정
- [ ] storylike 반환값 수정
- [ ] story 검색, 최신순 필드값 이름 수정
