### ISSUE TITLE
팔로잉-팔로워 페이지 수정

### ISSUE THREAD

**Issue by youngsikkk** [sdp-tech/SASM_FE#463]
## Description
- 팔로워가 있음에도 확인 안되는 오류 발생
- 팔로워 페이지 변경 시 같은 데이터 입력되는 오류 발생
- 팔로잉 페이지에서 검색이 안되는 오류 발생

## To-Do
- [x] 팔로워 확인 가능하게 수정
- [x] 페이지 변경 시 데이터 불러오게끔 수정
- [x] 팔로잉 페이지에서 검색이 안되는 오류 수정
