### ISSUE TITLE
웹 페이지 UI 개선

### ISSUE THREAD

**Issue by youngsikkk** [sdp-tech/SASM_FE#476]
## Description
- 웹 페이지의 UI를 개선

## To-Do
- [x] 큐레이션 모달창 개선
- [x] 큐레이션 스토리 선택 시 알림 기능
- [x] 큐레이션  UI 개선
- [x] 큐레이션 디테일 UI 개선
- [x] 맵 UI 개선
- [x] 스토리 UI 개선
- [x] 스토리 디테일 UI 개선
- [x] 기타 

# ETC
생각나는 것이 있으면 추가할 예정
