### ISSUE TITLE
Feat story api url

### ISSUE THREAD

**Issue by mysoo** [sdp-tech/SASM_FE#92]
## Description
서버와 연동할 story api url 구현.
## To-Do
- [x] story list api url 구현하기.
- [x] story detail api url 구현하기.
- [x] story detail ui 구현하기.
