### ISSUE TITLE
Feat search

### ISSUE THREAD

**Issue by mysoo** [sdp-tech/SASM_FE#99]
## Description
search 구현
## To-Do
- [x] place list search
- [x] story list search
- [x] 결과 없을 경우 다른 UI 띄우기
